services:
  frontend:
    build:
      context: ./frontend
      target: without_user
      dockerfile: Dockerfile.local
    environment:
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=0
    volumes:
      - ./frontend:/app
      - ./openapi:/openapi
    working_dir: /app
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/app
      - ./openapi:/openapi
    working_dir: /app
    ports:
      - "8080:8080"
    command: go run ./cmd/server
