services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
      args:
        - host_user_name=${host_user_name}
        - host_group_name=${host_group_name}
        - host_uid=${host_uid}
        - host_gid=${host_gid}
    volumes:
      - ./frontend:/app
      - ./openapi:/openapi
    working_dir: /app
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    volumes:
      - ./backend:/app
      - ./openapi:/openapi
    working_dir: /app
    ports:
      - "8080:8080"
    command: go run cmd/server/main.go
